### ISSUE TITLE
Shipnames center problem

### ISSUE THREAD

**Issue by ChristophSteinberg** [ChristophSteinberg/shiprandomizer#2]
die schiffsnamen werden von links nach rechts generiert 
und stehen mal etwas weiter links wenn der name kürzer ist,
wenn er länger ist dann ragt er über die mitte hinaus

ist es möglich dass die namen von der mitte aus generiert werden   bsp: GRAF <xxx> SPEE
so startet die suche immer am 1. buchstaben  xxx>"G" RAF SPEE

**Comment by ChristophSteinberg** [comment]
bzw, dass der name einfach richtig in der mitte bleibt, egal wie lange der name ist

**Comment by marklechtermann** [comment]
https://shiprandomizer.de/ :-D

Am Fr., 30. Dez. 2022 um 15:25 Uhr schrieb Graf_d ***@***.***
